#!/usr/bin/env bash
: ${NGINX_PORT:=1345}

if [[ -f .cid ]]; then
  docker stop `cat .cid`
  docker rm   `cat .cid`
  rm .cid
fi

docker run \
  -p ${NGINX_PORT}:80 \
  --restart=unless-stopped \
  --cidfile .cid \
  --name REACT-TEST \
  -v $(pwd):/usr/share/nginx/html:ro \
  -d nginx:alpine
